version: "2"
linters:
  default: none
  enable:
    - dupl
    - dupword
    - err113
    - errcheck
    - errname
    - errorlint
    - forcetypeassert
    - godot
    - gosec
    - govet
    - ineffassign
    - noctx
    - nonamedreturns
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - whitespace
    - wrapcheck
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gomodguard
    - gomodguard_v2
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - nolintlint
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
