---
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: nibbled
    binary: nibbled
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo

homebrew_casks:
  - name: nibbled
    ids:
      - archives
    homepage: "https://github.com/kgaughan/nibbled"
    repository:
      owner: kgaughan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Keith Gaughan
      email: k@stereochro.me
    description: "A server for the Gopher protocol"
    license: "MIT"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    manpages:
      - nibbled.1
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nibbled"]
          end

archives:
  - formats:
      - tar.gz
    id: archives
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - nibbled.1

nfpms:
  - id: packages
    file_name_template: >-
      {{ .PackageName }}-{{ .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    description: |-
      A server for the Gopher protocol.
    homepage: "https://github.com/kgaughan/nibbled"
    maintainer: "Keith Gaughan <k+nibbled@stereochro.me>"
    bindir: /usr/libexec
    contents:
      - src: nibbled.1
        dst: /usr/share/man/man1/nibbled.1
    license: MIT
    formats:
      - rpm
    overrides:
      rpm:
        dependencies:
          - shared-mime-info

kos:
  - build: nibbled
    base_image: gcr.io/distroless/static:nonroot
    annotations:
      org.opencontainers.image.title: nibbled
      org.opencontainers.image.description: "A server for the Gopher protocol. Almost meta."
      org.opencontainers.image.vendor: "Keith Gaughan"
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.url: https://github.com/kgaughan/nibbled
      org.opencontainers.image.source: https://github.com/kgaughan/nibbled
      org.opencontainers.image.documentation: https://kgaughan.github.io/nibbled/
      org.opencontainers.image.version: "{{ .Tag }}"
      org.opencontainers.image.revision: "{{ .Commit }}"
      org.opencontainers.image.created: "{{ .Date }}"
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - ghcr.io/kgaughan
    tags:
      - "{{ if not .Prerelease }}latest{{ end }}"
      - "{{.Tag}}"
    creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    bare: true
    base_import_paths: true
    preserve_import_paths: false
    disable: "{{ .IsSnapshot }}"

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
