.TH NIBBLED 1 "26 Jun 2023" "0.1.0"
.SH NAME
nibbled \- a server for the Gopher protocol
.SH SYNOPSIS
nibbled [-version] [-port PORT] [-root PATH] [-hostname HOST]
.SH DESRIPTION
nibbled is a Gopher daemon with full support for gopherfiles.
.SH OPTIONS
.TP
.B -version
Display current version information.
.TP
.B -port PORT
Port to bind to (defaults to 70).
.TP 
.B -root PATH
Root directory of the server (defaults to /srv/gopher).
.TP 
.B -hostname HOST
Hostname to bind to (defaults to localhost).
.SH BUGS
None known.
.SH AUTHOR
Keith Gaughan <k+nibbled@stereochro.me>
