---
name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: uses: actions/setup-go@v5

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59.1
        args: --issues-exit-code=0
        only-new-issues: true
